version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test-restapi-authorizer"
s3_prefix = "test-restapi-authorizer"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
